# Generated by Django 3.1.7 on 2021-05-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210521_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='visible',
            new_name='visibility',
        ),
    ]
