# Generated by Django 4.1.6 on 2023-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_oidc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
