# Generated by Django 3.1.7 on 2021-06-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_auto_20210611_1218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="status",
            field=models.CharField(
                choices=[("U", "Upload"), ("R", "Ready"), ("E", "Error")], default="U", max_length=2
            ),
        ),
    ]
