# Generated by Django 3.1.7 on 2021-07-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_auto_20210612_1930"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=256)),
                ("hash_id", models.CharField(max_length=256)),
            ],
        ),
    ]
